import os, sys
import numpy as np

def find_source(sigma):
    string_to_write = \
'''
## example input file (for ver. 2.1.5)
## generated by glafic -d

## setting primary parameters
omega     0.300000
lambda	  0.700000
weos	  -1.000000
hubble	  0.700000
prefix	  findsrc_%d
xmin	  -2.000000
ymin	  -2.000000
xmax	  2.000000
ymax	  2.000000
pix_ext   0.0100000
pix_poi   0.0100000
maxlev	  5

## define lenses and sources
startup 1 0 1
lens sie   1 %d  0 0 0.5249 69.7385 0.0 0.0
point 5.07  -0.5 0
end_startup

## for optimizations
## can be ignored unless you do opts
start_setopt
0 0 0 0 0 0 0 0 
0 1 1
end_setopt

## execute commands
start_command

readobs_point point.dat
optimize

quit
'''%(sigma, sigma)

    with open('./findsrc_%d.glafic'%sigma, 'w') as f:
        f.write(string_to_write)

    os.system('../glafic ./findsrc_%d.glafic'%sigma)

    # read the result
    savefile = 'findsrc_%d_optresult.dat'%sigma

    with open('./findsrc_%d_optresult.dat'%sigma, 'r') as f:
        for line in f:
#            print(line.strip())
            if line.startswith('point'):
                print(line.split())
                _, zs, xs, ys = line.strip().split()

    return float(xs), float(ys)

def compute_mu_and_thetaE(sigma, xs, ys):
    xs, ys = find_source(sigma)

    string_to_write = \
'''
## example input file (for ver. 2.1.5)
## generated by glafic -d

## setting primary parameters
omega     0.300000
lambda	  0.700000
weos	  -1.000000
hubble	  0.700000
prefix	  findimg_%d
xmin	  -2.000000
ymin	  -2.000000
xmax	  2.000000
ymax	  2.000000
pix_ext   0.0100000
pix_poi   0.0100000
maxlev	  5

## define lenses and sources
startup 1 0 1
lens sie   1 %d  0 0 0.5267 68.8965 0.0 0.0
point 5.07  %.6f  %.6f
end_startup

## for optimizations
## can be ignored unless you do opts
start_setopt
0 0 0 0 0 0 0 0 
0 1 1
end_setopt

## execute commands
start_command

calcein 5.07
findimg
quit
'''%(sigma, sigma, xs, ys)

    with open('./findimg_%d.glafic'%sigma, 'w') as f:
        f.write(string_to_write)

    os.system('../glafic ./findimg_%d.glafic'%sigma)

    # read theta E
    theta_E_dat = np.loadtxt('findimg_%d_ein.dat'%sigma)

    theta_E = theta_E_dat[2]

    # read mu
    mu_dat = np.loadtxt('findimg_%d_point.dat'%sigma)
#    print(mu_dat)

    if mu_dat[0][0]>1:
        mu = np.nan

    else:
        mu = mu_dat[1][2]

    return mu, theta_E

def list_mu_thetaE():

    mulist = []
    thetaElist = []

    sigmalist = range(100,200,1)

    for sigma in range(100,200,1):
        xs, ys = find_source(sigma)

        mu, theta = compute_mu_and_thetaE(sigma, xs, ys)

        mulist.append(mu)
        thetaElist.append(theta)

    np.savetxt('muthetaE.txt', [sigmalist, mulist, thetaElist])

if __name__=='__main__':
#    xs, ys = find_source(100)
#    print(xs, ys)

#    mu, theta = compute_mu_and_thetaE(100, xs, ys)
#    print(mu, theta)
    list_mu_thetaE()
